CREATE SEQUENCE TRAB_S_INSTITUICAO START WITH 1;

CREATE TABLE TRAB_INSTITUICOES (
  ID_INSTITUICAO NUMBER DEFAULT TRAB_S_INSTITUICAO.NEXTVAL,
  NOME VARCHAR(80),
  CONSTRAINT TRAB_PK_CLIENT PRIMARY KEY(ID_INSTITUICAO)
);

CREATE SEQUENCE TRAB_S_RECURSO START WITH 1;

CREATE TABLE TRAB_RECURSOS (
  ID_RECURSO NUMBER DEFAULT TRAB_S_RECURSO.NEXTVAL,
  CAPACIDADE NUMBER,
  ID_INSTITUICAO NUMBER,
  CONSTRAINT TRAB_PK_RECURSO PRIMARY KEY(ID_RECURSO)
);

ALTER TABLE TRAB_RECURSOS ADD CONSTRAINT TRAB_FK_ID_INSTITUICAO_RECURSO FOREIGN KEY(ID_INSTITUICAO) REFERENCES TRAB_INSTITUICOES;

CREATE SEQUENCE TRAB_S_PROGRAMAS START WITH 1;

CREATE TABLE TRAB_PROGRAMAS (
  ID_PROGRAMA NUMBER DEFAULT TRAB_S_PROGRAMAS.NEXTVAL,
  NOME VARCHAR(255) NOT NULL,
  MEM_CONSUMIDA_APR NUMBER DEFAULT 0,
  CONSTRAINT TRAB_PK_PROGRAMAS PRIMARY KEY(ID_PROGRAMA)
);

CREATE SEQUENCE TRAB_S_INSTANCIA START WITH 1;

CREATE TABLE TRAB_INSTANCIAS (
  ID_INSTANCIA NUMBER DEFAULT TRAB_S_INSTANCIA.NEXTVAL,
  ID_RECURSO NUMBER,
  ID_PROGRAMA NUMBER,
  CONSTRAINT TRAB_PK_INSTANCIAS PRIMARY KEY(ID_INSTANCIA)
);

ALTER TABLE TRAB_INSTANCIAS ADD CONSTRAINT FK_ID_RECURSO_INSTANCIA FOREIGN KEY(ID_RECURSO) REFERENCES TRAB_RECURSOS;

ALTER TABLE TRAB_INSTANCIAS ADD CONSTRAINT FK_ID_PROGRAMA_INSTANCIA FOREIGN KEY(ID_PROGRAMA) REFERENCES TRAB_PROGRAMAS ON DELETE CASCADE;

CREATE SEQUENCE TRAB_S_FILA START WITH 1;

CREATE TABLE TRAB_FILAS (
  ID_FILA NUMBER DEFAULT TRAB_S_FILA.NEXTVAL,
  ID_INSTANCIA NUMBER,
  CONSTRAINT TRAB_PK_FILAS PRIMARY KEY(ID_FILA)
);

ALTER TABLE TRAB_FILAS ADD CONSTRAINT TRAB_FK_ID_INSTANCIA_FILA FOREIGN KEY(ID_INSTANCIA) REFERENCES TRAB_INSTANCIAS ON DELETE CASCADE;

CREATE SEQUENCE TRAB_S_ALUNO START WITH 1;

CREATE TABLE TRAB_ALUNOS (
  ID_ALUNO NUMBER DEFAULT TRAB_S_ALUNO.NEXTVAL,
  NOME VARCHAR(255),
  EMAIL VARCHAR(255),
  SENHA VARCHAR(64),
  CONSTRAINT PK_ALUNOS PRIMARY KEY(ID_ALUNO),
  CONSTRAINT U_EMAIL UNIQUE(EMAIL)
);

CREATE SEQUENCE TRAB_S_ALUNOS_FILA START WITH 1;

CREATE TABLE TRAB_ALUNOS_FILA (
  ID_ALUNOS_FILA NUMBER DEFAULT TRAB_S_ALUNOS_FILA.NEXTVAL,
  ID_USUARIO NUMBER,
  ID_FILA NUMBER,
  DATA_ENTRADA DATE DEFAULT SYSDATE,
  DATA_SAIDA DATE,
  COMANDO CLOB,
  CONSTRAINT PK_ALUNOS_FILA PRIMARY KEY(ID_ALUNOS_FILA)
);

ALTER TABLE TRAB_ALUNOS_FILA ADD CONSTRAINT TRAB_FK_ID_ALUNO_FILA FOREIGN KEY(ID_USUARIO) REFERENCES TRAB_ALUNOS ON DELETE CASCADE;

ALTER TABLE TRAB_ALUNOS_FILA ADD CONSTRAINT TRAB_FK_ID_FILA_ALUNO FOREIGN KEY(ID_FILA) REFERENCES TRAB_FILAS ON DELETE CASCADE;

CREATE TABLE TRAB_ALUNO_FILA_INSTANCIA (
  INICIOU_EM DATE DEFAULT SYSDATE,
  ID_ALUNO_FILA NUMBER,
  ID_INSTANCIA NUMBER,
  TERMINOU_EM DATE,
  CONSTRAINT PK_ALUNO_FILA_INSTANCIA PRIMARY KEY(INICIOU_EM)
);

ALTER TABLE TRAB_ALUNO_FILA_INSTANCIA ADD CONSTRAINT TRAB_FK_ID_AF_INSTANCIA FOREIGN KEY(ID_ALUNO_FILA) REFERENCES TRAB_ALUNOS_FILA ON DELETE CASCADE;

ALTER TABLE TRAB_ALUNO_FILA_INSTANCIA ADD CONSTRAINT TRAB_FK_ID_INSTANCIA_ALUNO FOREIGN KEY(ID_INSTANCIA) REFERENCES TRAB_INSTANCIAS ON DELETE CASCADE;

CREATE SEQUENCE TRAB_S_MENU START WITH 1;

CREATE TABLE TRAB_MENU (
  ID_ITEM_MENU NUMBER DEFAULT TRAB_S_MENU.nextval,
  TITULO VARCHAR(255),
  LINK VARCHAR(255),
  METODO VARCHAR(10),
  CONSTRAINT PK_ITEM_MENU PRIMARY KEY(ID_ITEM_MENU)
);
